### ISSUE TITLE
Performance issue due to Symbol.isConcatSpreadable set

### ISSUE THREAD

**Issue by infinity-naveen** [ljharb/safe-array-concat#2]
# Description
We have been facing high **CPU** utilisation issues in our projects since April 2023. On debugging, we found that many dependencies were updated at that time (e.g. `util.promisify`, `promise.prototype.finally`, `object.getownpropertydescriptors`, etc.). And all of these started using `safe-array-concat` package. On further deep-driving, we observed that loading of this package safe-array-concat is impacting performance of Array `concat` function by around 20x in our whole application, and since concat() operation is used at lot of places in our code, it caused significant increase on our server's CPU utilisation.

# Root Cause
On analysing `safe-array-concat` source code, we found culprit line of code:
https://github.com/ljharb/safe-array-concat/blob/main/index.js#L16

`empty[isConcatSpreadable] = true;`

Actually, this code is also **not the root cause**, here `Symbol.isConcatSpreadable` is used as per requirement. Actual root cause is the **V8 Engine** (which is powering **NodeJs**). As per it's current implementation, if we set `Symbol.IsConcatSpreadable` to any array or object (even such single usage will trigger it), it will make all subsequent usages of Array.concat() slower in whole application.

Reference: https://github.com/v8/v8/blob/bf4b542a1b31bbe8106e394b1dbeff02571dff4b/src/builtins/builtins-array.cc#L1542

## Additional Context
In our case in all projects, the only such usage of symbol (where we are setting it to any value/array) is in this package code. As soon as we require safe-array-concat in our app, above mentioned line is executed & all subsequent concat() operations' performance is impacted.

# Steps to Reproduce Issue

Code:

```
const loadPackage = process.env.loadPackage==="true" || false;
const count = process.env.count || 100;

if (loadPackage) {
    require('safe-array-concat');
}

const runScript = () => {
    console.log(`Running test`);

    // creating sample array of 50k size with dummy data
    const sampleArray = [];
    const arraySize = 1000*50;
    for (let i = 0; i<arraySize; i++) sampleArray.push(i);

    // Actual test:
    console.time("concatOperation");
    for (let i =0; i<count; i++) {
        sampleArray.concat(sampleArray); // <--- Testing impact on this operation's performance
    }
    console.timeEnd("concatOperation");
}

runScript();
```

**Execution results**:
`loadPackage=true count=200 node safe-test.js` :: 2.5 sec
`loadPackage=false count=200 node safe-test.js` :: 113 ms
`loadPackage=true count=500 node safe-test.js` :: 6.3 sec
`loadPackage=false count=500 node safe-test.js` :: 275 ms

**Comment by infinity-naveen** [comment]
Since, our projects are tightly coupled with this package, can we please do some code changes, so that `Symbol.isConcatSpreadable` is not set on app initialisation. Here is a PR we also tried to fix it, this is solving our use-case, please have a look if it can help here: 
https://github.com/ljharb/safe-array-concat/pull/3

**Comment by ljharb** [comment]
I'd be happy to make an improvement here to the package's performance in v8 if it doesn't sacrifice any correctness or robustness. I'll take a look at the PR.

**Comment by infinity-naveen** [comment]
Thanks @ljharb for the quick response and action. Issue is now resolved after upgrading to latest version.

**Comment by ljharb** [comment]
Awesome, glad to hear it!
