### ISSUE TITLE
Que tal adicionar um .npmignore para ignorar alguns arquivos da biblioteca?

### ISSUE THREAD

**Issue by gabrielogregorio** [ljharb/safe-array-concat#4]
Hello,

I would like to propose adding a `.npmignore` file to the project. This would allow publishing to npm to ignore files that are not essential for deployment to production environments, such as:

```txt
test/
.github/
.eslintrc
.nycrc
```

These files are generally only used during development and are not needed in the final distribution of the library. Implementing this change would help reduce the library package size, thus optimizing efficiency for end users.

I include a screenshot below to illustrate the location of the files mentioned in the current repository:

![Captura de tela de 2023-11-28 08-27-23](https://github.com/ljharb/safe-array-concat/assets/48621655/e0da6bfd-7869-4133-88da-5d3573f48ca1)

Thank you for your attention and I am available to discuss this suggestion further.

**Comment by ljharb** [comment]
I have one, autogenerated at publish time via the `npmignore` package. However, all these files are critical and are intentionally included, so that `npm explore foo && npm install && npm test` always works.
